import {createRequire} from 'node:module';
import assert from 'node:assert/strict';
const require = createRequire(import.meta.url), W = require('../public/walk-space.js'), E = require('../public/evac.js');
const S = require('../public/survey-preview.js'), R = require('../public/routing.js');
const K = [111320 * Math.cos(10.51 * Math.PI / 180), 110540];
const at = (x, y) => [123.712 + x / K[0], 10.508 + y / K[1]];
const box = (x, y, w = 8, h = 8) => [[at(x - w / 2, y - h / 2), at(x + w / 2, y - h / 2), at(x + w / 2, y + h / 2), at(x - w / 2, y + h / 2), at(x - w / 2, y - h / 2)]];
const house = (id, x, y, w, h) => ({type: 'Feature', properties: {id}, geometry: {type: 'Polygon', coordinates: box(x, y, w, h)}});
const buildings = [house('home', 0, 0), house('obstacle', 25, 0)];
const space = W.create(buildings);
const path = space.route(at(0, 0), at(50, 0), {ignore: 0, maxLength: 80});
assert.ok(path?.length > 2, 'detours around the unburned building');
assert.ok(path.every((p, i) => !i || space.clear(path[i - 1], p, 0)), 'every detour segment clears footprints');
assert.equal(space.route(at(0, 0), at(25, 0), {ignore: 0}), null, 'never ends inside another building');
assert.equal(space.route(at(0, 0), at(50, 0), {ignore: 0, maxLength: 50}), null, 'does not invent a shortcut when the detour exceeds the limit');
const water = W.create([], [box(25, 0, 10, 20)]);
const dry = water.route(at(0, 0), at(50, 0));
assert.ok(dry.length > 2 && dry.every((p, i) => !i || water.clear(dry[i - 1], p)), 'routes around water');
assert.equal(W.create([], [box(25, 0, 10, 200)]).route(at(0, 0), at(50, 0)), null, 'an impassable water barrier gives no path');
const snapped = space.snap(at(25, 0));
assert.ok(snapped && space.clear(snapped, snapped), 'GPS point is moved out of a footprint within the bounded tolerance');
const concave = {type: 'Feature', properties: {id: 'L'}, geometry: {type: 'Polygon', coordinates: [[at(10, 0), at(20, 0), at(20, 4), at(14, 4), at(14, 14), at(10, 14), at(10, 0)]]}};
const corner = W.create([concave]);
assert.equal(corner.clear(at(9, 5), at(16, 3)), false, 'a diagonal may not cut a building corner');
const road = {type: 'Feature', properties: {id: 'main', from_node: 'south', to_node: 'north', alley_wd: 4, walk_ok: 1, access_ok: 1, highway: 'tertiary'}, geometry: {type: 'LineString', coordinates: [at(50, -60), at(50, 60)]}};
const inputs = {features: buildings, densities: [0, 0], households: [1, 1], roads: [road]};
const frames = [{minute: 0, states: [1, 0]}], before = JSON.stringify(frames);
const original = E.prepare(inputs).evaluate(frames), preview = E.prepare({...inputs, walkingSpace: space}).evaluate(frames);
const old = original.groups.find(g => g.i === 0), now = preview.groups.find(g => g.i === 0);
assert.equal(now.status, 'safe');
assert.ok(now.accessEnd > 1, 'the connector retains its bends for animation');
assert.ok(now.arrive > old.arrive, 'travel time includes the longer detour');
assert.ok(now.times.every((t, i) => !i || t >= now.times[i - 1]), 'timestamps stay ordered');
assert.ok(now.coords.every((p, i) => !i || space.clear(now.coords[i - 1], p, i <= now.accessEnd ? 0 : -1)), 'whole route avoids buildings');
assert.equal(JSON.stringify(frames), before, 'evacuation does not mutate fire frames');
const alley = (id, coords) => ({type: 'Feature', properties: {id, width_m: 1, access: 'walk'}, geometry: {type: 'LineString', coordinates: coords}});
const joined = S.joinCrossings([alley('horizontal', [at(-20, 0), at(20, 0)]), alley('vertical', [at(0, -20), at(0, 20)])], []);
assert.equal(joined.length, 4, 'crossing walked alleys become four connected sections');
const graph = R.buildGraph(R.prepareNetwork([], joined, {nodeM: 0.35, lineM: 0.5}), [], []);
const centreNodes = [...graph.coords].filter(([, p]) => Math.hypot((p.lonlat[0] - at(0, 0)[0]) * K[0], (p.lonlat[1] - at(0, 0)[1]) * K[1]) < 0.1);
assert.equal(centreNodes.length, 1, 'the crossing shares one junction');
assert.equal(graph.graph.adj.get(centreNodes[0][0]).length, 4, 'all four directions connect');
console.log('Walking preview checks passed: footprint detours, water barriers, corner safety, bounded GPS adjustment, timings and unchanged fire frames.');
